### PR TITLE
Choices should accept callable to generate options

### PR DESCRIPTION
**Pull request by bmwant**
### Description
`choices` field on questions should accept a callable as documentation states.

### Changes
* Allow choices to be a callable returning list of choices based on internal logic
* Update readme
* Update tests

### CODE REVIEW

**Comment by CITGuru** [comment]
I guess its already supported. You can call a method to generate choices. So what are you trying to say?

**Comment by bmwant** [comment]
@CITGuru yes, you can call a function, but there is no ability to make choices dynamic based on previous answers. I want to limit (or extend) options based on previously provided answers to make workflow more flexible.

**Comment by bmwant** [comment]
@CITGuru please let me know whether this change is feasible for current repo. I  need to base another library on this code, so probably will need to use my own fork if this change will not go into any release. Any feedback is appreciated too.

**Comment by CITGuru** [comment]
Okay, this might go into dev release for the main time before its pushed to pypi. I'll work on it.

**Comment by cyberbeast** [comment]
Any updates on this? I am looking for this exact functionality. Also, thank you for this @CITGuru :)

**Pull request merged**
