### PR TITLE
Make PyPI show readme with formatting

### PR DESCRIPTION
**Pull request by MartinThoma**

### CODE REVIEW

**Comment by MartinThoma** [comment]
Currently, PyPI does not format the content: https://pypi.org/project/PyInquirer/

Make it nice, like I have done with other projects:

* https://pypi.org/project/clana/
* https://pypi.org/project/lidtk/
* https://pypi.org/project/mpu/

**Comment by MartinThoma** [comment]
One needs to upload a new version to PyPI, of course, to see it.

**Comment by CITGuru** [comment]
@MartinThoma Thanks for the contribution. The build fails I might have to take a close look.

**Comment by MartinThoma** [comment]
```
_______________ ERROR collecting tests/test_example_checkbox.py ________________
ImportError while importing test module '/home/travis/build/CITGuru/PyInquirer/tests/test_example_checkbox.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/python.py:513: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:152: in exec_module
    exec(co, module.__dict__)
tests/test_example_checkbox.py:5: in <module>
    from .helpers import create_example_fixture, keys
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:152: in exec_module
    exec(co, module.__dict__)
tests/helpers.py:23: in <module>
    from PyInquirer import style_from_dict, Token
E   ImportError: cannot import name 'style_from_dict'
=========================== short test summary info ============================
ERROR tests/test_example_checkbox.py
```

I can't see how this is related to my PR.

**Comment by drabard** [comment]
This import issue is fixed in PR #93

**Pull request merged**
